kind = "mobile"
previewPath = "/"
title = "Mi Bancolombia"
version = "1.0.0"
id = "artifacts/mi-bancolombia"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/" ]
localPort = 22949

[services.development]
run = "pnpm --filter @workspace/mi-bancolombia run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mi-bancolombia", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mi-bancolombia", "run", "serve" ]

[services.env]
PORT = "22949"
BASE_PATH = "/"
